use_frameworks!

platform :ios, '9.0'

target 'BGECycleScrollView_Example' do
  pod 'BGECycleScrollView', :path => '../'

  target 'BGECycleScrollView_Tests' do
    inherit! :search_paths

    
  end
end
